### ISSUE TITLE
Any reason the TCPTransport can't just be a NetTransport?

### ISSUE THREAD

**Issue by mitchellh** [armon/go-chord#3]
I don't see any TCP specific things other than the `SetDelay` stuff which can easily be guarded by type checks. Any reason why you can't just use a `net.Conn` here? 

This would improve flexibility quite a lot. I don't see a strong use case why you would want this except to maybe onion-wrap a net.Conn for various reasons, but I also don't see what you're buying by restricting to TCP.

I realize the paper probably expects a reliable transport underneath, but UDP on localhost is reliable for example and I don't see why that wouldn't work with the packet sizes here.

EDIT: Actually, you probably would never want to use UDP, but it was just a poor example. I think the point in my issue still stands.

**Comment by euforia** [comment]
I know this issue is closed but ran across it during my usage of the library and had a related question. 

I've implemented a gRPC `Transport` that takes a `Listener` and `grpc.Server` as args.  The implementation design is referenced from `TCPTransport` and is nearly identical.  

This allows to run other services along side chord on the same listener.  I was wondering if this is the right approach of is there a better route?  

Here's a link to the transport in case needed - https://github.com/euforia/go-chord/blob/master/grpc.go
